name: motiongpt
channels:
  - menpo
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py39h5a03fae_7
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.5.7=hbcca054_0
  - certifi=2023.5.7=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - ffmpeg=4.3.2=hca11adc_0
  - freetype=2.10.4=h0708190_1
  - freetype-py=2.4.0=pyhd8ed1ab_0
  - future=0.18.3=pyhd8ed1ab_0
  - geos=3.10.2=h9c3ff4c_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - h5py=3.7.0=py39h737f45e_0
  - hdf5=1.10.6=h3ffc7dd_1
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h166bdaf_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=2.2.1=h9c3ff4c_0
  - libdeflate=1.7=h7f98852_5
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.3.0=hf544144_1
  - libwebp-base=1.2.2=h7f98852_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - mapbox_earcut=1.0.0=py39hf939315_3
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.6=py39h417a72b_1
  - mkl_random=1.2.2=py39h417a72b_1
  - ncurses=6.4=h6a678d5_0
  - nettle=3.6=he412f7d_0
  - networkx=3.1=pyhd8ed1ab_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1u=h7f8727e_0
  - osmesa=12.2.2.dev=0
  - packaging=23.1=pyhd8ed1ab_0
  - pip=23.0.1=py39h06a4308_0
  - pooch=1.7.0=pyha770c72_3
  - pyglet=1.5.27=py39hf3d152e_3
  - pyopengl=3.1.6=pyhd8ed1ab_1
  - pyrender=0.1.45=pyh8a188c0_3
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.16=h7a1cb2a_2
  - python_abi=3.9=2_cp39
  - readline=8.2=h5eee18b_0
  - setuptools=66.0.0=py39h06a4308_0
  - shapely=1.8.2=py39h73b9895_1
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - trimesh=3.22.3=pyhd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - wheel=0.38.4=py39h06a4308_0
  - x264=1!161.3030=h7f98852_1
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - absl-py==1.4.0
    - accelerate==0.18.0
    - aiobotocore==2.5.0
    - aiohttp==3.8.4
    - aioitertools==0.11.0
    - aiosignal==1.3.1
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - async-timeout==4.0.2
    - attrs==23.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - bitsandbytes==0.38.1
    - bleach==6.0.0
    - blessed==1.20.0
    - botocore==1.29.76
    - cachetools==5.3.0
    - cffi==1.15.1
    - charset-normalizer==3.1.0
    - chumpy==0.70
    - click==8.1.3
    - clip==1.0
    - cmake==3.26.3
    - comm==0.1.3
    - croniter==1.3.14
    - cycler==0.11.0
    - datasets==2.11.0
    - dateutils==0.6.12
    - debugpy==1.6.7
    - decorator==5.1.1
    - deepdiff==6.3.0
    - defusedxml==0.7.1
    - dill==0.3.6
    - docstring-parser==0.15
    - executing==1.2.0
    - fairscale==0.4.13
    - fastapi==0.88.0
    - fastjsonschema==2.16.3
    - filelock==3.12.0
    - fire==0.5.0
    - fqdn==1.5.1
    - frozenlist==1.3.3
    - fsspec==2023.4.0
    - ftfy==6.1.1
    - google-auth==2.17.3
    - google-auth-oauthlib==1.0.0
    - grpcio==1.54.0
    - h11==0.14.0
    - hiq-python==1.1.12
    - huggingface-hub==0.13.4
    - imageio==2.9.0
    - importlib-metadata==6.5.0
    - importlib-resources==5.12.0
    - inquirer==3.1.3
    - ipykernel==6.22.0
    - ipython==8.13.2
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.6
    - isoduration==20.11.0
    - itsdangerous==2.1.2
    - jedi==0.18.2
    - jinja2==3.1.2
    - jmespath==1.0.1
    - jsonargparse==4.20.1
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-client==8.2.0
    - jupyter-console==6.6.3
    - jupyter-core==5.3.0
    - jupyter-events==0.6.3
    - jupyter-server==2.5.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.7
    - kiwisolver==1.4.4
    - lightning==2.0.0
    - lightning-cloud==0.5.33
    - lightning-fabric==2.0.1.post0
    - lightning-utilities==0.8.0
    - lit==16.0.1
    - markdown==3.4.3
    - markdown-it-py==2.2.0
    - markupsafe==2.1.2
    - matplotlib==3.4.3
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - mistune==2.0.5
    - mpmath==1.3.0
    - multidict==6.0.4
    - multiprocess==0.70.14
    - nbclassic==1.0.0
    - nbclient==0.7.4
    - nbconvert==7.3.1
    - nbformat==5.8.0
    - nest-asyncio==1.5.6
    - notebook==6.5.4
    - notebook-shim==0.2.3
    - numpy==1.24.2
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - oauthlib==3.2.2
    - ordered-set==4.1.0
    - pandas==2.0.0
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.5.0
    - platformdirs==3.5.0
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.38
    - protobuf==3.20.0
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py-itree==0.0.19
    - pyarrow==11.0.0
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pycparser==2.21
    - pydantic==1.10.7
    - pygments==2.15.1
    - pyjwt==2.6.0
    - pyllama==0.0.9
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-editor==1.0.4
    - python-json-logger==2.0.7
    - python-multipart==0.0.6
    - pytorch-lightning==2.0.1.post0
    - pytz==2023.3
    - pyyaml==6.0
    - pyzmq==25.0.2
    - qtconsole==5.4.2
    - qtpy==2.3.1
    - readchar==4.0.5
    - regex==2023.3.23
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.3.4
    - rsa==4.9
    - s3fs==2023.4.0
    - scipy==1.10.1
    - send2trash==1.8.2
    - sentencepiece==0.1.97
    - smplx==0.1.28
    - sniffio==1.3.0
    - soupsieve==2.4.1
    - stack-data==0.6.2
    - starlette==0.22.0
    - starsessions==1.3.0
    - sympy==1.11.1
    - tensorboard==2.12.2
    - tensorboard-data-server==0.7.0
    - tensorboard-plugin-wit==1.8.1
    - termcolor==2.2.0
    - terminado==0.17.1
    - tinycss2==1.2.1
    - tokenizers==0.13.3
    - torch==2.0.0
    - torchmetrics==0.11.4
    - torchvision==0.15.1
    - tornado==6.3.1
    - tqdm==4.65.0
    - traitlets==5.9.0
    - transformers==4.28.1
    - triton==2.0.0
    - typeshed-client==2.2.0
    - typing-extensions==4.5.0
    - tzdata==2023.3
    - uri-template==1.2.0
    - urllib3==1.26.15
    - uvicorn==0.21.1
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - websockets==11.0.2
    - werkzeug==2.2.3
    - widgetsnbextension==4.0.7
    - wrapt==1.15.0
    - xxhash==3.2.0
    - yarl==1.8.2
    - zipp==3.15.0
    - zstandard==0.21.0
